APPLICATION = lab3_adc

RIOTBASE ?= $(CURDIR)/../..
BOARD ?= openmote-cc2538
PROGRAMMER ?= cc2538-bsl

USEMODULE += xtimer

FEATURES_REQUIRED += periph_timer
FEATURES_REQUIRED += periph_gpio

include $(RIOTBASE)/Makefile.include
